import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ['latin'],
  weight: ['100','200', '300', '500', '600', '700', '800', '900'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Clerk + Supabase Integration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
